### ISSUE TITLE
Read access denied at createLogLines

### ISSUE THREAD

**Issue by basi01** [mendix/AuditTrailModule#33]
Hi. I noticed that when the current user has no read access to some members of a audited entity saving it fails.
The line that fails is:
```
		// get current and previous id
		final IMendixIdentifier currentId = member.getValue(currentcontext);
```

For instance
```
Caused by: com.mendix.basis.objectmanagement.member.MemberAccessDeniedException: Read access denied for member 'Cover.Cover_CoverVendorUser' of object 'Cover.Cover'
	at com.mendix.basis.objectmanagement.MendixObjectMemberImpl.checkReadAccess(MendixObjectMemberImpl.java:161)
	at com.mendix.basis.objectmanagement.MendixObjectMemberImpl.getValue(MendixObjectMemberImpl.java:208)
	at audittrail.log.CreateLogObject.createReferenceLogLine(CreateLogObject.java:286)
	at audittrail.log.CreateLogObject.createLogLines(CreateLogObject.java:224)
	at audittrail.log.CreateLogObject.createAuditLogItems(CreateLogObject.java:183)
	at audittrail.log.CreateLogObject.createAuditLogItems(CreateLogObject.java:70)
	at audittrail.actions.CreateLogRecordOfObject.executeAction(CreateLogRecordOfObject.java:43)
	at audittrail.actions.CreateLogRecordOfObject.executeAction(CreateLogRecordOfObject.java:1)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:58)
```

Why are you using `currentcontext` instead of `sudocontext` here. I don't think `currentcontext` is good for anything in this module.
__Version 9.0.1

**Comment by dahfjkg** [comment]
We addressed this issue in the latest release of the module: 8.1.2 for Mendix 8 and 9.0.2 for Mendix 9
